### ISSUE TITLE
Repo activity

### ISSUE THREAD

**Issue by drizk1** [scimas/Druid.jl#4]
Is this repo maintained? Or is it pretty functional/ stable enough  and not requiring maintenance? I was thinking of using it to add Druid as a backend for another package (TidierDB.jl) ?

**Comment by scimas** [comment]
Hi Daniel, no, the repo is not maintained. I haven't used Julia in almost 3 years and Druid for about a year.

The original reason for writing the package was for some personal experiments, and I believe I had written it well enough that everything was at least functional. I vaguely remember that I hadn't put any checks about the version of the Druid cluster being queried. That would be relevant if Druid.jl is used with some older versions of Druid which didn't support all of the native queries that were supported by the latest Druid at the time of writing Druid.jl. I know Druid itself has had many major releases since then, but I don't know what and if anything has changed with the query API itself. So those checks may or may not have become necessary at this point.

I am not planning on doing any more work on the package at the moment. Experiment and see if any work is needed on it. I'd be willing to transfer ownership if you want to take up the maintenance.

**Comment by drizk1** [comment]
Thank you for getting back to me! For a personal experiment, it's quite impressive. 

At this time, I'm not sure I have the technical chops or bandwidth to maintain this package, but perhaps if there is demand for Druid, I will circle back. 

If you ever find yourself wandering back to Julia, take a peek at [Tidier.jl](https://github.com/TidierOrg)

Thank you!
